/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

//import com.example.S3AckTestUtil;

public class App {
    public String getGreeting() {
//        return S3AckTestUtil.getS3Message();
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
