name: Endor Labs Dependency and Secrets Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    permissions:
      security-events: write # Upload Sarif artifact to GitHub
      contents: read # Checkout a private repository
      actions: read # Required for private repos to upload Sarif files
      id-token: write # Used for keyless authentication with Endor Labs
      pull-requests: write # Allows PR commenting for violations
    runs-on: ubuntu-latest
    env:
      TENANT_NAME: "leonardo-learn"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENDOR_JS_ENABLE_TSSERVER: false

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle 

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Endor Labs Scan (PR Mode)
      if: github.event_name == 'pull_request'
      uses: endorlabs/github-action@v1
      with:
        namespace: ${{ env.TENANT_NAME }} # Replace with actual Endor Labs tenant namespace
        scan_dependencies: true
        pr: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Endor Labs Scan (Push & Manual Runs)
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: endorlabs/github-action@v1
      with:
        namespace: ${{ env.TENANT_NAME }} # Replace with actual Endor Labs tenant namespace
        scan_dependencies: true
        pr: false
        log_level: debug
        additional_args: "--quick-scan --languages=java --bypass-host-check --call-graph-languages=java"

    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build

